apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accelerate-api
  description: Accelerate springboot REST API
spec:
  type: openapi
  lifecycle: experimental
  owner: accelerate-team
  system: accelerate-system
  definition:
    $json: https://github.com/FaissalElfid/backstage-manifest/blob/main/api/accelerate.json